name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    env:
      PYTHONUNBUFFERED: "1"
      MOCK_MODE: "1"
      BACKEND_HOST: "http://127.0.0.1:8000"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Launch backend (mock mode)
        run: |
          nohup uvicorn backend.app:app --host 127.0.0.1 --port 8000 &> backend.log &
          for i in {1..30}; do
            curl -sSf ${BACKEND_HOST}/docs >/dev/null && break
            sleep 1
          done
          curl -sSf ${BACKEND_HOST}/docs >/dev/null

      - name: Run unit tests
        run: pytest -q

      - name: Hit /compare (mock)
        run: |
          COMPARERESP=$(curl -sS -X POST ${BACKEND_HOST}/compare \
            -H "Content-Type: application/json" \
            -d '{"prompt":"Say hi in one sentence","models":["gpt-4o","claude-3-opus"],"temperature":0.2}')
          echo "$COMPARERESP" | python scripts/validate_compare.py

      - name: Hit /experiment (mock)
        run: |
          EXPRESP=$(curl -sS -X POST ${BACKEND_HOST}/experiment \
            -H "Content-Type: application/json" \
            -d '{"prompt":"Explain quantum computing in simple terms.","models":["gpt-4o","claude-3-opus"],"temperatures":[0.0,0.7],"system_prompts":[null]}')
          echo "$EXPRESP" | python scripts/validate_experiment.py

      - name: Upload logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: backend-logs
          path: backend.log